let data;let currentId;const $=s=>document.querySelector(s);const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function start(){data=await fetch('data.json').then(r=>r.json());renderMetrics();renderList();renderEvaluation();selectIncident(data.incidents[0].id);bindNav()}
function renderMetrics(){const d=data.dataset;$('#metrics').innerHTML=[[d.incidents,'Synthetic incidents'],[d.logs.toLocaleString()+'+','Structured logs'],[d.knowledge_documents,'Grounding documents'],[d.automatic_actions,'Automatic actions']].map(([v,l])=>`<div class="metric"><strong>${v}</strong><span>${l}</span></div>`).join('')}
function renderList(){const list=$('#incident-list');$('#incident-count').textContent=data.incidents.length+' demos';list.innerHTML=data.incidents.map(i=>`<button class="incident" data-id="${i.id}"><div class="incident-top"><strong>${i.id} · ${escapeHtml(i.service)}</strong><span class="badge ${i.severity==='SEV-1'?'sev1':'sev2'}">${i.severity}</span></div><p>${escapeHtml(i.title)}</p></button>`).join('');list.querySelectorAll('.incident').forEach(b=>b.onclick=()=>selectIncident(b.dataset.id))}
function selectIncident(id){currentId=id;document.querySelectorAll('.incident').forEach(b=>b.classList.toggle('active',b.dataset.id===id));const i=data.incidents.find(x=>x.id===id);$('#investigation').innerHTML=`<div class="incident-header"><div><p class="eyebrow">${i.id} · ${escapeHtml(i.service)}</p><h2>${escapeHtml(i.title)}</h2><p>${escapeHtml(i.alert_summary)}</p></div><button class="diagnose" id="diagnose">Run diagnosis</button></div><div class="signal-grid"><div class="signal"><strong>${i.metrics.error_rate}</strong><span>Error rate</span></div><div class="signal"><strong>${i.metrics.p95_latency}</strong><span>p95 latency</span></div><div class="signal"><strong>${i.metrics.availability}</strong><span>Availability</span></div></div><div class="trace" id="trace">${i.trace.map((s,n)=>`<div class="step" data-step="${n}">${escapeHtml(s.label)}</div>`).join('')}</div><div id="report-placeholder"><div class="guardrail">Click “Run diagnosis” to replay the evidence-grounded local investigation.</div></div>`;$('#diagnose').onclick=runDiagnosis}
async function runDiagnosis(){const i=data.incidents.find(x=>x.id===currentId);const button=$('#diagnose');button.disabled=true;button.textContent='Investigating…';for(let n=0;n<i.trace.length;n++){await new Promise(r=>setTimeout(r,360));document.querySelector(`[data-step="${n}"]`).classList.add('done')}renderReport(i);button.textContent='Replay diagnosis';button.disabled=false}
function renderReport(i){const r=i.report;const cited=i.evidence.filter(e=>r.evidence_ids.includes(e.evidence_id));$('#report-placeholder').innerHTML=`<section class="report"><h3>Root-cause analysis <span class="confidence">${Math.round(r.confidence_score*100)}% confidence</span></h3><div class="cause">${escapeHtml(r.probable_root_cause)}</div><div class="report-grid"><div class="report-item"><span>Suggested remediation</span><p>${escapeHtml(r.suggested_fix)}</p></div><div class="report-item"><span>Rollback recommendation</span><p>${escapeHtml(r.rollback_recommendation)}</p></div><div class="report-item"><span>Prevention action</span><p>${escapeHtml(r.prevention_action)}</p></div><div class="report-item"><span>Safety boundary</span><p>Human review required. No action was executed.</p></div></div><h3>Cited evidence</h3><div class="evidence">${cited.map(e=>`<div class="evidence-item"><div class="evidence-id">${escapeHtml(e.evidence_id)}</div>${escapeHtml(e.summary)}</div>`).join('')}</div><div class="guardrail">✓ Every citation maps to retrieved evidence · ✓ No-action policy passed</div></section>`}
function renderEvaluation(){$('#evaluation-grid').innerHTML=data.evaluation_targets.map(e=>`<div class="eval-card"><div><h3>${escapeHtml(e.Metric)}</h3><p>Acceptance target: ${escapeHtml(e.Target)}</p></div><span class="pending">${escapeHtml(e['Published result'])}</span></div>`).join('')}
function bindNav(){document.querySelectorAll('.nav-button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const evalView=b.dataset.view==='evaluation';$('#incidents-view').classList.toggle('hidden',evalView);$('#evaluation-view').classList.toggle('hidden',!evalView)})}
start().catch(error=>{$('#investigation').innerHTML=`<p>Demo failed to load: ${escapeHtml(error.message)}</p>`})

